### ISSUE TITLE
possible regression between 11.3 and 11.4

### ISSUE THREAD

**Issue by zhl146** [jina-ai/discoart#142]
Getting this error when I try to schedule init_scale

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/discoart/__main__.py", line 13, in <module>
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/usr/local/lib/python3.8/dist-packages/discoart/api.py", line 33, in create
    create(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discoart/create.py", line 185, in create
    _args = load_config(user_config=kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discoart/config.py", line 60, in load_config
    cfg[k] = int(v)
ValueError: invalid literal for int() with base 10: '[1000]*1000'
`

**Comment by zhl146** [comment]
actually, it's throwing that error even when I don't define init_scale, backing out to 0.10.15 allows it to run

**Comment by zhl146** [comment]
looks like 11.3 is fine as well

**Comment by hanxiao** [comment]
what is the code to reproduce? i tried the following on 11.4 no problem

```python
from discoart import create

da = create(init_scale=1000)
```
