### ISSUE TITLE
call me back ? Github's goal is to distribute code that works and not the other way around, right?

### ISSUE THREAD

**Issue by DarkSynx** [jina-ai/discoart#165]
Similar on windows
it would be nice to offer a video from A to Z that explains how to operate, obviously it does not work!
and it's problematic when the goal of github is to provide something functional.
-----------
```shell
/usr/local/lib/python3.9/dist-packages/discoart/helper.py:129: UserWarning: 
!!!!CUDA is not available. DiscoArt is running on CPU. `create()` will be unbearably slow on CPU!!!!
Please switch to a GPU device. If you are using Google Colab, then free tier would just work.
            
  warnings.warn(
2022-08-10 16:40:07,069 - discoart - INFO - preparing models...
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/usr/local/lib/python3.9/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.9/dist-packages/lpips/weights/v0.1/vgg.pth
2022-08-10 16:40:15,114 - discoart - INFO - 
W&B dashboard is disabled. To enable the online dashboard for tracking losses, gradients, 
scheduling tracking, please set `WANDB_MODE=online` before running/importing DiscoArt. e.g.

    import os
    os.environ['WANDB_MODE'] = 'online'

    from discoart import create
    create(...)

2022-08-10 16:40:15,114 - discoart - INFO - creating artworks `discoart-2fa0f7bc18ba11edba9a0800276247d2` (0/4)...
  0%|                                                                                                      | 0/250 [02:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/toor/discart/app.py", line 3, in <module>
    da = create()
  File "/usr/local/lib/python3.9/dist-packages/discoart/create.py", line 217, in create
    da = do_run(
  File "/usr/local/lib/python3.9/dist-packages/discoart/runner.py", line 414, in do_run
    for j, sample in enumerate(samples):
  File "/usr/local/lib/python3.9/dist-packages/guided_diffusion/gaussian_diffusion.py", line 897, in ddim_sample_loop_progressive
    out = sample_fn(
  File "/usr/local/lib/python3.9/dist-packages/guided_diffusion/gaussian_diffusion.py", line 674, in ddim_sample
    out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/guided_diffusion/respace.py", line 102, in condition_score
    return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/guided_diffusion/gaussian_diffusion.py", line 399, in condition_score
    eps = eps - (1 - alpha_bar).sqrt() * cond_fn(
  File "/usr/local/lib/python3.9/dist-packages/guided_diffusion/respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/discoart/runner.py", line 207, in cond_fn
    masked_weights = normalize_fn(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 4620, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
RuntimeError: "clamp_min_cpu" not implemented for 'Half'
root@lx:/home/toor/discart# 
```

**Comment by Smit1237** [comment]
Try reading error output next time.
