### ISSUE TITLE
create() error 

### ISSUE THREAD

**Issue by Lexa070301** [jina-ai/discoart#170]
Traceback (most recent call last):
  File "/home/alexey/Desktop/images.py", line 3, in <module>
    da = create()
  File "/home/alexey/.local/lib/python3.10/site-packages/discoart/create.py", line 191, in create
    from .helper import (
  File "/home/alexey/.local/lib/python3.10/site-packages/discoart/helper.py", line 21, in <module>
    from clip.simple_tokenizer import SimpleTokenizer, whitespace_clean, basic_clean
  File "/home/alexey/.local/lib/python3.10/site-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/home/alexey/.local/lib/python3.10/site-packages/clip/clip.py", line 10, in <module>
    from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize
  File "/home/alexey/.local/lib/python3.10/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/home/alexey/.local/lib/python3.10/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/home/alexey/.local/lib/python3.10/site-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "/home/alexey/.local/lib/python3.10/site-packages/torchvision/io/__init__.py", line 5, in <module>
    from ..utils import _log_api_usage_once
  File "/home/alexey/.local/lib/python3.10/site-packages/torchvision/utils.py", line 21, in <module>
    @torch.no_grad()
AttributeError: module 'torch' has no attribute 'no_grad'

Google suggested that I need to update the touch module, but this did not help

**Comment by AdamThahir** [comment]
Could you provide your torch module version and installed cuda version?

For reference: 

Torch:
`python -c "import torch;print(torch.__version__)"`

cuda:
`nvcc --version`

**Comment by hanxiao** [comment]
pytorch issue, pytorch version too old, out of scope of discoart
