### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by eformx** [jina-ai/discoart#42]
Running on CPU or GPU does not work on local machine. Installed via Github desktop. Error message appeared after model is cached.  Tried to install cuda which runs disco diffusion, but not discoart?

discoart_test.py
from discoart import create
da = create()

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\sites\discoart\discoart\helper.py", line 15, in <module>
    from open_clip import SimpleTokenizer
  File "D:\sites\discoart\venv\lib\site-packages\open_clip\__init__.py", line 2, in <module>
    from .loss import ClipLoss
  File "D:\sites\discoart\venv\lib\site-packages\open_clip\loss.py", line 2, in <module>
    import torch.distributed.nn
  File "D:\sites\discoart\venv\lib\site-packages\torch\distributed\nn\__init__.py", line 1, in <module>
    from .api.remote_module import RemoteModule
  File "D:\sites\discoart\venv\lib\site-packages\torch\distributed\nn\api\remote_module.py", line 25, in <module>
    from torch.distributed.rpc.internal import _internal_rpc_pickler
  File "D:\sites\discoart\venv\lib\site-packages\torch\distributed\rpc\internal.py", line 12, in <module>
    from torch._C._distributed_rpc import _get_current_rpc_agent
ModuleNotFoundError: No module named 'torch._C._distributed_rpc'; 'torch._C' is not a package
python-BaseException`

**Comment by hanxiao** [comment]
please update via `pip install -U discoart` and retry, if necessary create a new ticket. thx

**Comment by Cinc11** [comment]
I had the same problem. Did you solve it?
