### ISSUE TITLE
CUDA memory error since last update

### ISSUE THREAD

**Issue by jwelch1324** [jina-ai/discoart#43]
Since pulling the latest `jinaai/discoart` docker image -- my parameter set which worked without issue before is now causing CUDA OOM errors.  

The parameter set being used is as follows:
```python
params = {
        'text_prompts': ['A bunny rabbit','4k resolution, cinematic lighting'],
        'init_image': None,
        'width_height': [512, 512],
        'skip_steps': 10,
        'steps': 1000,
        'cut_ic_pow': 1,
        'init_scale': 1000,
        'clip_guidance_scale': 80000,
        'tv_scale': 0,
        'range_scale': 150,
        'sat_scale': 0,
        'cutn_batches': 4,
        'diffusion_model': '512x512_diffusion_uncond_finetune_008100',
        'use_secondary_model': True,
        'diffusion_sampling_mode': 'ddim',
        'perlin_init': False,
        'perlin_mode': 'mixed',
        'seed': 3012672161,
        'eta': 0.8,
        'clamp_grad': True,
        'clamp_max': 0.05,
        'randomize_class': True,
        'clip_denoised': False,
        'fuzzy_prompt': False,
        'rand_mag': 0.05,
        'cut_overview': '[12]*400+[4]*600',
        'cut_innercut': '[4]*400+[12]*600',
        'cut_icgray_p': '[0.2]*400+[0]*600',
        'display_rate': 10,
        'n_batches': 1,
        'batch_size': 1,
        'batch_name': 'bunny_rabbit',
        'clip_models': ['ViT-B-32::openai', 'RN50x4::openai'],
        'name_docarray': 'test'
    }
```

This is running on a small 1060 -- but this worked without issue prior to pulling this new image -- is there a setting that has changed which may have increased the memory footprint? 

The digest of the image that worked is
```
REPOSITORY          TAG                               DIGEST                                                                    IMAGE ID       CREATED       SIZE
jinaai/discoart     latest                            sha256:aad5c0e51b601897c035e615e15a90e7263270c6da22fd294ff07f32e964dce0   60d78ef5ab4a   2 weeks ago   14.1GB

```
but oddly I cannot find the tag of an image on dockerhub that has this hash anymore. 

EDIT: I pulled `jinaai/discoart:0.0.18` and the above params work again -- i'll test other versions and see if I can find where the change occurred.

**Comment by jwelch1324** [comment]
On Dockerhub the digests are all the same up to 6.3 -- so everything up to 6.3 presumably works as well -- 

Can confirm that tag 0.6.4 is where the change occurred that is causing the OOM error with these params

**Comment by hanxiao** [comment]
> but oddly I cannot find the tag of an image on dockerhub that has this hash anymore.

`latest` is default, there is no need to specify it, it just a default tag by Docker specification

> Can confirm that tag 0.6.4 is where the change occurred that is causing the OOM error with these params

This is the comparison between 0.6.3 and 0.6.4, i don't see a significant change here

https://github.com/jina-ai/discoart/compare/v0.6.3...v0.6.4

**Comment by hanxiao** [comment]
also, could you show the full error trace of OOM, i'd like to see where it comes from?

**Comment by jwelch1324** [comment]
> latest is default, there is no need to specify it, it just a default tag by Docker specification

Understood -- what I meant was that the digest listed on docker hub going many versions back is identical... the change doesn't occur until the 0.6.3 -> 0.6.4 transition (and the digest I pulled 2 weeks ago isn't around anymore 🤷 )

![image](https://user-images.githubusercontent.com/4706333/179578638-d471a48f-44f0-419d-a4d5-9b17b75a8e8a.png)

Notice the digest is `10bd4c249f59` for several versions prior to 0.6.4 -- this is all from https://hub.docker.com/r/jinaai/discoart/tags?page=1&ordering=last_updated

either way I just confirmed that pulling 0.6.3 directly and running the query there does not result in the OOM error.



> This is the comparison between 0.6.3 and 0.6.4, i don't see a significant change here

This is very strange -- because there is definitely a difference in the user experience -- in 0.6.3 and prior the following header is not visible in the jupyter notebook while the query is running 
![image](https://user-images.githubusercontent.com/4706333/179578315-61c763ec-33e4-4e28-a000-e1db3509ff3a.png)

-- all that is shown in prior versions is the progress bar and the docarray name.

>also, could you show the full error trace of OOM, i'd like to see where it comes from?

Ahh yes sorry I should have done that at the start -- here is the stacktrace

```
2022-07-18 18:27:48,370 - discoart - ERROR - CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 5.93 GiB total capacity; 5.17 GiB already allocated; 3.31 MiB free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discoart/create.py", line 176, in create
    do_run(_args, (model, diffusion, clip_models, secondary_model), device=device)
  File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 336, in do_run
    for j, sample in enumerate(samples):
  File "/root/.cache/discoart/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 897, in ddim_sample_loop_progressive
    out = sample_fn(
  File "/root/.cache/discoart/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 674, in ddim_sample
    out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
  File "/root/.cache/discoart/guided_diffusion/guided_diffusion/respace.py", line 102, in condition_score
    return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
  File "/root/.cache/discoart/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 399, in condition_score
    eps = eps - (1 - alpha_bar).sqrt() * cond_fn(
  File "/root/.cache/discoart/guided_diffusion/guided_diffusion/respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 214, in cond_fn
    model_stat['clip_model'].encode_image(clip_in).float()
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 435, in encode_image
    return self.visual(image)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 187, in forward
    x = self.layer3(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 58, in forward
    out = self.bn3(self.conv3(out))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 5.93 GiB total capacity; 5.17 GiB already allocated; 3.31 MiB free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by jwelch1324** [comment]
Ok so this is good to know! -- Also thanks for the insight into what `use_secondary_model` actually does :D 

Based on what you are saying though I think it implies that in general 6GB of VRAM is going to be insufficient moving forward for 512x512 resolution (using the clip models I have shown here -- maybe others work I haven't tried) -- is this correct? I tried changing the setting of `use_secondary_model` in my parameters (it was `True` so i set it to `False`) and I still get an OOM error though it occurs in a different code location -- it is inside the `unet.py` module now

``` 2022-07-18 19:14:03,792 - discoart - ERROR - CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 5.93 GiB total capacity; 5.24 GiB already allocated; 9.31 MiB free; 5.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/discoart/create.py", line 176, in create
     do_run(_args, (model, diffusion, clip_models, secondary_model), device=device)
   File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 338, in do_run
     for j, sample in enumerate(samples):
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 897, in ddim_sample_loop_progressive
     out = sample_fn(
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 674, in ddim_sample
     out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 102, in condition_score
     return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 399, in condition_score
     eps = eps - (1 - alpha_bar).sqrt() * cond_fn(
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 128, in __call__
     return self.model(x, new_ts, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 194, in cond_fn
     out = diffusion.p_mean_variance(
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 91, in p_mean_variance
     return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 260, in p_mean_variance
     model_output = model(x, self._scale_timesteps(t), **model_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 128, in __call__
     return self.model(x, new_ts, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
     return forward_call(*input, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/unet.py", line 661, in forward
     h = module(h, emb)
   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
     return forward_call(*input, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/unet.py", line 77, in forward
     x = layer(x)
   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
     return forward_call(*input, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/unet.py", line 297, in forward
     return checkpoint(self._forward, (x,), self.parameters(), self.use_checkpoint)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/nn.py", line 138, in checkpoint
     return func(*inputs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/unet.py", line 303, in _forward
     h = self.attention(qkv)
   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
     return forward_call(*input, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/unet.py", line 352, in forward
     weight = th.softmax(weight.float(), dim=-1).type(weight.dtype)
 RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 5.93 GiB total capacity; 5.24 GiB already allocated; 9.31 MiB free; 5.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by hanxiao** [comment]
What i tried [to express here](https://github.com/jina-ai/discoart/issues/43#issuecomment-1188152126) is `use_secondary_model=True` uses higher memory than `use_secondary_model=False`

**Comment by jwelch1324** [comment]
> What i tried [to express here](https://github.com/jina-ai/discoart/issues/43#issuecomment-1188152126) is `use_secondary_model=True` uses higher memory than `use_secondary_model=False`

Understood -- however even with it set to `False` a different OOM error is raised -- I was not sure then if the secondary model aspect was related to the new OOM error?

**Comment by hanxiao** [comment]
i just find a point of potential improvement in `p_mean_variance` implementation, which can be used to reduce VRAM footprint, will work on this tmr

**Comment by hanxiao** [comment]
btw, my finding is irrelevant to OP, 6GB VRAM is nonetheless too small 😅
