### ISSUE TITLE
The size of tensor a (50) must match the size of tensor b (82) at non-singleton dimension 0

### ISSUE THREAD

**Issue by jwelch1324** [jina-ai/discoart#44]
## Description
Pulling latest `jinai/discoart` image and running the following query results in the error displayed in the title.

### Query
```python
import requests
data = {
        "execEndpoint":"/create",
        "parameters":{
        'text_prompts': ['A bunny rabbit','4k resolution, cinematic lighting'],
        'init_image': None,
        'width_height': [512, 512],
        'skip_steps': 10,
        'steps': 1000,
        'cut_ic_pow': 1,
        'init_scale': 1000,
        'clip_guidance_scale': 80000,
        'tv_scale': 0,
        'range_scale': 150,
        'sat_scale': 0,
        'cutn_batches': 4,
        'diffusion_model': '512x512_diffusion_uncond_finetune_008100',
        'use_secondary_model': True,
        'diffusion_sampling_mode': 'ddim',
        'perlin_init': False,
        'perlin_mode': 'mixed',
        'seed': 3012672161,
        'eta': 0.8,
        'clamp_grad': True,
        'clamp_max': 0.05,
        'randomize_class': True,
        'clip_denoised': False,
        'fuzzy_prompt': False,
        'rand_mag': 0.05,
        'cut_overview': '[12]*400+[4]*600',
        'cut_innercut': '[4]*400+[12]*600',
        'cut_icgray_p': '[0.2]*400+[0]*600',
        'display_rate': 10,
        'n_batches': 1,
        'batch_size': 1,
        'batch_name': 'bunny_rabbit',
        'clip_models': ['ViT-B-32::openai', 'RN50x4::openai'],
        'name_docarray': 'test'
    }
}
res = requests.post("http://0.0.0.0:51001/post",json=data)
```

The stacktrace on the console: 
```bash
  0%|          | 0/990 [00:02<?, ?it/s]
2022-07-18 19:02:44,146 - discoart - ERROR - The size of tensor a (50) must match the size of tensor b (82) at non-singleton dimension 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discoart/create.py", line 176, in create
    do_run(_args, (model, diffusion, clip_models, secondary_model), device=device)
  File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 338, in do_run
    for j, sample in enumerate(samples):
  File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 897, in ddim_sample_loop_progressive
    out = sample_fn(
  File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 674, in ddim_sample
    out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 102, in condition_score
    return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/gaussian_diffusion.py", line 399, in condition_score
    eps = eps - (1 - alpha_bar).sqrt() * cond_fn(
  File "/usr/local/lib/python3.8/dist-packages/guided_diffusion/respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discoart/runner.py", line 216, in cond_fn
    model_stat['clip_model'].encode_image(clip_in).unsqueeze(1)
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 435, in encode_image
    return self.visual(image)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 189, in forward
    x = self.attnpool(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/open_clip/model.py", line 81, in forward
    x = x + self.positional_embedding[:, None, :].to(x.dtype)  # (HW+1)NC
RuntimeError: The size of tensor a (50) must match the size of tensor b (82) at non-singleton dimension 0
```

## Steps to reproduce
1. Pull Latest Docker Image
```bash
docker pull jinaai/discoart:latest
```
2. Run Container as Service
```bash
docker run --entrypoint "python" -p 51001:51001 -v $(pwd):/home/jovyan/ -v /data/home/jwelch/.cache:/root/.cache --gpus all jinaai/discoart -m discoart serv
```

3. Execute the script shown in the above query from the local machine running the container.

### System Specs
```
OS: Ubuntu 20.04
Linux picard 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
GPU: Nvidia RTX Titan - 24GB
Python Version (outside of container): 3.10.4
```

**Comment by jwelch1324** [comment]
Has to do with the clip model selection I am using -- minimal script to reproduce this error 

```python
import requests
params = { 'clip_models': ['ViT-B-32::openai', 'RN50x4::openai']}
res = requests.post("http://0.0.0.0:51001/post",json=data)
```

This clip model selection worked with the docker images which were pinned to 0.0.x (see https://github.com/jina-ai/discoart/issues/43#issuecomment-1188097890)

**Comment by hanxiao** [comment]
thanks for pointing that out! will dig into this

**Comment by hanxiao** [comment]
yes and you should give it try
