### ISSUE TITLE
Running create() in Colab Notebook results in the following error

### ISSUE THREAD

**Issue by paranoiks** [jina-ai/discoart#65]
The error doesn't stop the image processing or the image preview

```Exception in thread Thread-2747:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 501, in plot_image_sprites
    ] = _d.tensor
ValueError: could not broadcast input array from shape (63,51,3) into shape (0,51,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discoart/runner.py", line 447, in _plot_sample
    keep_aspect_ratio=True,
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 506, in plot_image_sprites
    ) from ex
ValueError: Bad image tensor. Try different `image_source` or `channel_axis`

Exception in thread Thread-2799:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 501, in plot_image_sprites
    ] = _d.tensor
ValueError: could not broadcast input array from shape (57,46,3) into shape (0,46,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discoart/runner.py", line 447, in _plot_sample
    keep_aspect_ratio=True,
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 506, in plot_image_sprites
    ) from ex
ValueError: Bad image tensor. Try different `image_source` or `channel_axis`

Exception in thread Thread-2855:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 501, in plot_image_sprites
    ] = _d.tensor
ValueError: could not broadcast input array from shape (57,46,3) into shape (0,46,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discoart/runner.py", line 447, in _plot_sample
    keep_aspect_ratio=True,
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 506, in plot_image_sprites
    ) from ex
ValueError: Bad image tensor. Try different `image_source` or `channel_axis`

Exception in thread Thread-2907:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 501, in plot_image_sprites
    ] = _d.tensor
ValueError: could not broadcast input array from shape (52,42,3) into shape (0,42,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discoart/runner.py", line 447, in _plot_sample
    keep_aspect_ratio=True,
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 506, in plot_image_sprites
    ) from ex
ValueError: Bad image tensor. Try different `image_source` or `channel_axis`

Exception in thread Thread-2917:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 501, in plot_image_sprites
    ] = _d.tensor
ValueError: could not broadcast input array from shape (52,42,3) into shape (0,42,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discoart/runner.py", line 447, in _plot_sample
    keep_aspect_ratio=True,
  File "/usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py", line 506, in plot_image_sprites
    ) from ex
ValueError: Bad image tensor. Try different `image_source` or `channel_axis````

**Comment by hanxiao** [comment]
In a new Colab free tier env I can not reproduce
<img width="838" alt="image" src="https://user-images.githubusercontent.com/2041322/180272547-fa7c7e9d-52b4-4298-b682-2f35f0a7f967.png">
