### ISSUE TITLE
server discoart inside Docker error args: "unknown argument `__results__`, misspelled?"

### ISSUE THREAD

**Issue by brokeDude2901** [jina-ai/discoart#67]
Hi, i'm having problems server Discoart with this error:
on client:
```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/jina/helper.py", line 1292, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/mixin.py", line 176, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/base/grpc.py", line 96, in _get_results
    logger=self.logger,
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/helper.py", line 81, in callback_exec
    raise BadServer(response.header)
jina.excepts.BadServer: request_id: "bdf9ac7a4f164f06ae1e4adac3d2ab9d"
status {
  code: ERROR
  description: "AttributeError(\'unknown argument `__results__`, misspelled?\')"
  exception {
    name: "AttributeError"
    args: "unknown argument `__results__`, misspelled?"
    stacks: "Traceback (most recent call last):\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py\", line 165, in process_data\n    return await self._data_request_handler.handle(requests=requests)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py\", line 155, in handle\n    return_data = await self._executor.__acall__(\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/jina/serve/executors/__init__.py\", line 289, in __acall__\n    return await self.__acall_endpoint__(req_endpoint, **kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/jina/serve/executors/__init__.py\", line 310, in __acall_endpoint__\n    return await func(self, **kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/jina/serve/executors/decorators.py\", line 207, in arg_wrapper\n    return await fn(executor_instance, *args, **kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/discoart/executors.py\", line 14, in create_artworks\n    await asyncio.get_event_loop().run_in_executor(None, self._create, parameters)\n"
    stacks: "  File \"/usr/lib/python3.8/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/discoart/executors.py\", line 19, in _create\n    return create(\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/discoart/create.py\", line 166, in create\n    _args = load_config(user_config=kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/dist-packages/discoart/config.py\", line 36, in load_config\n    raise AttributeError(f\'unknown argument `{k}`, misspelled?\')\n"
    stacks: "AttributeError: unknown argument `__results__`, misspelled?\n"
    executor: "DiscoArtExecutor"
  }
}
exec_endpoint: "/create"


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1306             try:
-> 1307                 return thread.result
   1308             except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)
2 frames
[/usr/local/lib/python3.7/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1310 
   1311                 raise BadClient(
-> 1312                     'something wrong when running the eventloop, result can not be retrieved'
   1313                 )
   1314         else:

BadClient: something wrong when running the eventloop, result can not be retrieved
```

on server:
```
DEBUG  discoart/rep-0@17 recv DataRequest at /create with    [07/21/22 21:47:49]
       id: bdf9ac7a4f164f06ae1e4adac3d2ab9d
ERROR  discoart/rep-0@17 AttributeError('unknown argument
       `__results__`, misspelled?')
        add "--quiet-error" to suppress the exception
       details
       ╭──────── Traceback (most recent call last) ────────╮
       │ /usr/local/lib/python3.8/dist-packages/jina/serv… │
       │ in process_data                                   │
       │                                                   │
       │   162 │   │   │   │   if self.logger.debug_enable │
       │   163 │   │   │   │   │   self._log_data_request( │
       │   164 │   │   │   │                               │
       │ ❱ 165 │   │   │   │   return await self._data_req │
       │   166 │   │   │   except (RuntimeError, Exception │
       │   167 │   │   │   │   self.logger.error(          │
       │   168 │   │   │   │   │   f'{ex!r}'               │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/jina/serv… │
       │ in handle                                         │
       │                                                   │
       │   152 │   │   )                                   │
       │   153 │   │                                       │
       │   154 │   │   # executor logic                    │
       │ ❱ 155 │   │   return_data = await self._executor. │
       │   156 │   │   │   req_endpoint=requests[0].header │
       │   157 │   │   │   docs=docs,                      │
       │   158 │   │   │   parameters=params,              │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/jina/serv… │
       │ in __acall__                                      │
       │                                                   │
       │   286 │   │   # noqa: DAR201                      │
       │   287 │   │   """                                 │
       │   288 │   │   if req_endpoint in self.requests:   │
       │ ❱ 289 │   │   │   return await self.__acall_endpo │
       │   290 │   │   elif __default_endpoint__ in self.r │
       │   291 │   │   │   return await self.__acall_endpo │
       │   292                                             │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/jina/serv… │
       │ in __acall_endpoint__                             │
       │                                                   │
       │   307 │   │                                       │
       │   308 │   │   with _summary:                      │
       │   309 │   │   │   if iscoroutinefunction(func):   │
       │ ❱ 310 │   │   │   │   return await func(self, **k │
       │   311 │   │   │   else:                           │
       │   312 │   │   │   │   return func(self, **kwargs) │
       │   313                                             │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/jina/serv… │
       │ in arg_wrapper                                    │
       │                                                   │
       │   204 │   │   │   │   async def arg_wrapper(      │
       │   205 │   │   │   │   │   executor_instance, *arg │
       │   206 │   │   │   │   ):  # we need to get the su │
       │       the self                                    │
       │ ❱ 207 │   │   │   │   │   return await fn(executo │
       │   208 │   │   │   │                               │
       │   209 │   │   │   │   self.fn = arg_wrapper       │
       │   210 │   │   │   else:                           │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/discoart/… │
       │ in create_artworks                                │
       │                                                   │
       │   11 │                                            │
       │   12 │   @requests(on='/create')                  │
       │   13 │   async def create_artworks(self, paramete │
       │ ❱ 14 │   │   await asyncio.get_event_loop().run_i │
       │   15 │                                            │
       │   16 │   def _create(self, parameters: Dict, **kw │
       │   17 │   │   from .create import create           │
       │                                                   │
       │ /usr/lib/python3.8/concurrent/futures/thread.py:… │
       │ in run                                            │
       │                                                   │
       │    54 │   │   │   return                          │
       │    55 │   │                                       │
       │    56 │   │   try:                                │
       │ ❱  57 │   │   │   result = self.fn(*self.args, ** │
       │    58 │   │   except BaseException as exc:        │
       │    59 │   │   │   self.future.set_exception(exc)  │
       │    60 │   │   │   # Break a reference cycle with  │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/discoart/… │
       │ in _create                                        │
       │                                                   │
       │   16 │   def _create(self, parameters: Dict, **kw │
       │   17 │   │   from .create import create           │
       │   18 │   │                                        │
       │ ❱ 19 │   │   return create(                       │
       │   20 │   │   │   skip_event=self.skip_event, stop │
       │   21 │   │   )                                    │
       │   22                                              │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/discoart/… │
       │ in create                                         │
       │                                                   │
       │   163 │   │   │   _kwargs.update(kwargs)          │
       │   164 │   │   _args = load_config(user_config=_kw │
       │   165 │   else:                                   │
       │ ❱ 166 │   │   _args = load_config(user_config=kwa │
       │   167 │                                           │
       │   168 │   save_config_svg(_args)                  │
       │   169                                             │
       │                                                   │
       │ /usr/local/lib/python3.8/dist-packages/discoart/… │
       │ in load_config                                    │
       │                                                   │
       │    33 │                                           │
       │    34 │   for k in list(user_config.keys()):      │
       │    35 │   │   if k not in cfg and k not in ('_sta │
       │ ❱  36 │   │   │   raise AttributeError(f'unknown  │
       │    37 │                                           │
       │    38 │   if user_config:                         │
       │    39 │   │   if user_config.get('cut_schedules_g │
       ╰───────────────────────────────────────────────────╯
       AttributeError: unknown argument `__results__`,
       misspelled?
```

My docker command is:
```
sudo docker run --name discoart --rm -p 8888:8888 -p 51001:51001 \
-v $HOME/private/diffusion_stuff/discoart_flow.yml:/root/discoart_flow.yml \
-v $HOME/jupyter_workspace:/root/jupyter_workspace/ \
-v $HOME/.cache_discoart:/root/.cache --gpus all jinaai/discoart \
bash -c "python -m discoart serve /root/discoart_flow.yml"
```
my discoart_flow.yml is:
```
jtype: Flow
with:
  protocol: grpc
  monitoring: true
  port: 51001
  port_monitoring: 51002  # prometheus monitoring port
  env:
    JINA_LOG_LEVEL: debug
    DISCOART_DISABLE_IPYTHON: 1
    DISCOART_DISABLE_RESULT_SUMMARY: 1
executors:
  - name: discoart
    uses: DiscoArtExecutor
#    env:
#      CUDA_VISIBLE_DEVICES: RR0:3  # change this if you have multiple GPU
#    replicas: 3  # change this if you have larger VRAM
  - name: poller
    uses: ResultPoller
```
my client Python code:
```
from jina import Client

c = Client(host='grpc://myserver:51001')

da = c.post(
    '/create',
    parameter={
        'name_docarray': 'mydisco-123',
        'text_prompts': [
            'A beautiful painting of a singular lighthouse',
            'yellow color scheme',
        ],
    },
)
```

**Comment by hanxiao** [comment]
fixed and rolled out in 0.7.11
